### ISSUE TITLE
Homepage mooi maken

### ISSUE THREAD

**Issue by nebbii** [nebbii/AlaBonteKoe#1]
(Van de to-do lijst van Rick)
maarten? :3

**Comment by ghost** [comment]
De homepage is "verbeterd"
- Logo en grijze gevlakte is lang en breed ipv. groot en vierkant
- Lettertype(titels zoals: Het Restaurant, Uitgaanscentrum & Bioscoop) hetzelfde als De Bonte Koe hoofdtitel
- Andere achtergrond bij: Uitgaanscentrum

Kan dit geclosed worden of moet er nog wat veranderd worden?

**Comment by nebbii** [comment]
Up to rick denk ik :3 hij vond dat er dingen beter aan moesten, maar ik weet niet zeker wat precies
